# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: cosmos-db-table-java-quickstart
metadata:
  template: cosmos-db-table-java-quickstart
services:
  web:
    project: ./src
    language: java
    host: containerapp
    docker:
      path: ./Dockerfile
      context: ./
pipeline:
  provider: github
